### ISSUE TITLE
 connect to the hotspot dashboard

### ISSUE THREAD

**Issue by aarrmmeenn30** [Panther-X/PantherDashboard#49]
How to connect to the hotspot dashboard, when I am not in the same network as the hotspot itself?

**Comment by qinfengling** [comment]
@aarrmmeenn30 The current dashboard does not support remote access and never will. Because we believe that any ability to connect through the Internet has a potential security risk, unless the user knows how to protect the device. Of course, if you want to access it remotely, you can also try some other methods, such as VPN, DMZ, etc., you can find the answer online or in the community.
